site_name: '${{values.component_id}}'
site_description: 'REST API service with health check and info endpoints named ${{values.component_id}} in the ${{values.environment}} environment'
repo_url: https://github.com/Shukriy/${{values.component_id}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Home: docs/index.md
  